# Configuration file for `pre-commit` (https://pre-commit.com/)

# To use pre-commit, first install globally with `pip install pre-commit`
# To install and activate the hooks, use `pre-commit install`
# By default, pre-commit only runs on modified files
# To run on all files, use `pre-commit run --all-files`
# To update all hooks, use `pre-commit autoupdate`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed
      - id: check-ast # checks whether the files parse as valid python
      - id: fix-byte-order-marker # fixes files which have a utf-8 byte-order marker
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
      - id: requirements-txt-fixer # sorts entries in requirements.txt
      - id: trailing-whitespace # trims trailing whitespace
      - id: check-json # checks json files for parseable syntax
      - id: check-yaml # checks yaml files for parseable syntax
      - id: check-toml # checks toml files for parseable syntax

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort # sort imports

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black # python code formatting

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff # python code linting

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy # static type checking
        additional_dependencies:
          - pydantic[dotenv]==1.8.1

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade # upgrade syntax for newer Python versions

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint # lints commit messages

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit # python security checks
        args: ["-c", "pyproject.toml"]
