# Configuration file for `pre-commit` (https://pre-commit.com/)

# To use pre-commit, first install globally with `pip install pre-commit`
# To install and activate the hooks, use `pre-commit install`
# By default, pre-commit only runs on modified files
# To run on all files, use `pre-commit run --all-files`

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-yaml

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/pylint
  rev: v2.12.2
  hooks:
  - id: pylint

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    additional_dependencies:
        - pydantic[dotenv]==1.8.1

- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.17.0
  hooks:
  - id: gitlint
