[tool.pytest.ini_options]
# pytest configuration: https://docs.pytest.org/en/latest/reference/customize.html#pyproject-toml
addopts = "--strict-markers"
testpaths = ["tests"]

[tool.mypy]
# mypy configuration: https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
disallow_untyped_decorators = false
explicit_package_bases = true
namespace_packages = true
strict = true
warn_return_any = true
warn_unused_configs = true
