[tool.pytest.ini_options]
# pytest configuration: https://docs.pytest.org/en/latest/reference/customize.html#pyproject-toml
addopts = "--strict-markers"
testpaths = ["tests"]

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.mypy]
# mypy configuration: https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
disallow_untyped_decorators = false
exclude = ["tests/"]
explicit_package_bases = true
namespace_packages = true
no_implicit_optional = true
strict = true # activates a bunch of strictness flags, see `mypy --help`
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
# Enable Pyflakes and pycodestyle rules
line-length = 120
select = ["E", "F"]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
