[tool.pytest.ini_options]
# pytest configuration: https://docs.pytest.org/en/latest/reference/customize.html#pyproject-toml
testpaths = [
  "tests",
]

[tool.black]
line-length = 120

[tool.mypy]
disallow_untyped_decorators = false
explicit_package_bases = true
namespace_packages = true
strict = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_errors = true
module = "importlib.*"
